### ISSUE TITLE
[Ehcmt]global：近期开发任务及故障修复

### ISSUE THREAD

**Issue by df7c5117** [zhxsu/zhxsu-index#2]
- [x] 1.ReadytoSign页面的完善、部分细节修改
- [x] 2.后台重置密码
- [x] 3.toSignUP页面的验证码完善
- [x] 4.index的SUsage入口准备关闭
- [x] 5.toSignUP页面的注册须知

**Comment by SmallOyster** [comment]
index的susage入口关闭是什么意思？

**Comment by SmallOyster** [comment]
导出Excel可能做不了了

**Comment by df7c5117** [comment]
噗233333

**Comment by SmallOyster** [comment]
已删除该项任务。
